#ifndef LED_H_GYX5PBBN
#define LED_H_GYX5PBBN

#include <avr/io.h>
#include <avr/iom32.h>

#define LED_CARS_PORT PORTA
#define LED_PEDS_PORT PORTB

#define LED_CARS_GRN (1 << 0)
#define LED_CARS_YEL (1 << 1)
#define LED_CARS_RED (1 << 2)

#define LED_PEDS_GRN (1 << 0)
#define LED_PEDS_YEL (1 << 1)
#define LED_PEDS_RED (1 << 2)

#define LED_CARS_GRN_ON ((LED_CARS_PORT) |= (LED_CARS_GRN))
#define LED_CARS_YEL_ON ((LED_CARS_PORT) |= (LED_CARS_YEL))
#define LED_CARS_RED_ON ((LED_CARS_PORT) |= (LED_CARS_RED))

#define LED_CARS_GRN_TGL ((LED_CARS_PORT) ^= (LED_CARS_GRN))
#define LED_CARS_YEL_TGL ((LED_CARS_PORT) ^= (LED_CARS_YEL))
#define LED_CARS_RED_TGL ((LED_CARS_PORT) ^= (LED_CARS_RED))

#define LED_CARS_GRN_OFF ((LED_CARS_PORT) &= ~(LED_CARS_GRN))
#define LED_CARS_YEL_OFF ((LED_CARS_PORT) &= ~(LED_CARS_YEL))
#define LED_CARS_RED_OFF ((LED_CARS_PORT) &= ~(LED_CARS_RED))

#define LED_PEDS_GRN_ON ((LED_PEDS_PORT) |= (LED_PEDS_GRN))
#define LED_PEDS_YEL_ON ((LED_PEDS_PORT) |= (LED_PEDS_YEL))
#define LED_PEDS_RED_ON ((LED_PEDS_PORT) |= (LED_PEDS_RED))

#define LED_PEDS_GRN_TGL ((LED_PEDS_PORT) ^= (LED_PEDS_GRN))
#define LED_PEDS_YEL_TGL ((LED_PEDS_PORT) ^= (LED_PEDS_YEL))
#define LED_PEDS_RED_TGL ((LED_PEDS_PORT) ^= (LED_PEDS_RED))

#define LED_PEDS_GRN_OFF ((LED_PEDS_PORT) &= ~(LED_PEDS_GRN))
#define LED_PEDS_YEL_OFF ((LED_PEDS_PORT) &= ~(LED_PEDS_YEL))
#define LED_PEDS_RED_OFF ((LED_PEDS_PORT) &= ~(LED_PEDS_RED))

#define LED_ALL_CLR \
  LED_CARS_GRN_OFF; \
  LED_CARS_RED_OFF; \
  LED_CARS_YEL_OFF; \
  LED_PEDS_GRN_OFF; \
  LED_PEDS_RED_OFF; \
  LED_PEDS_YEL_OFF;

#endif /* end of include guard: LED_H_GYX5PBBN */
